AllCops:
  DisplayCopNames: true
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'
    - 'Rakefile'
  NewCops: enable
  SuggestExtensions: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Style/SignalException:
  EnforcedStyle: only_raise
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SafeNavigation:
  Exclude:
    - lib/prawn/icon/interface.rb
Metrics/AbcSize:
  Max: 20
Naming/FileName:
  Exclude:
    - gemfiles/*.gemfile
