AllCops:
  DisplayCopNames: true
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'
    - 'Rakefile'
MethodLength:
  Max: 25
SignalException:
  EnforcedStyle: only_raise
Documentation:
  Enabled: false
RegexpLiteral:
  Enabled: false
SpaceAroundOperators:
  Enabled: false
FirstParameterIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Naming/FileName:
  Exclude:
    - gemfiles/*.gemfile
